store/config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get 'persons/profile'

  resources :items
  root 'welcome#index'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

store/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

store/app/models/item.rb
class Item < ApplicationRecord
end

store/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

store/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

store/app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.all
  end
  def show
    @item = Item.find(params[:id])
  end
  def new
  end
  def create
    @item = Item.new(params.require(:item).permit(:item_name, :description))

    @item.save
    redirect_to @item

  end

  private
  def item_params
    params.require(:item).permit(:item_name, :description)
  end
end

store/app/controllers/persons_controller.rb
class PersonsController < ApplicationController
  def profile
  end
end

store/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

store/app/helpers/application_helper.rb
module ApplicationHelper
end

store/app/helpers/items_helper.rb
module ItemsHelper
end

store/app/helpers/persons_helper.rb
module PersonsHelper
end

store/app/helpers/welcome_helper.rb
module WelcomeHelper
end

store/app/views/items/index.html.erb
<h1>List of items</h1>
<%= link_to 'New item', new_item_path %>
<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
  </tr>

  <% @items.each do |item| %>
      <tr>
        <td><%= item.item_name %></td>
        <td><%= item.description %></td>
        <td><%= link_to 'Show', item_path(item) %></td>
      </tr>
  <% end %>
</table>

store/app/views/items/new.html.erb
<h1>Item</h1>
<%= form_for :item, url: items_path do |f| %>
    <p>
      <%= f.label :item_name %><br>
      <%= f.text_field :item_name %>
    </p>

    <p>
      <%= f.label :description %><br>
      <%= f.text_area :description %>
    </p>

    <p>
      <%= f.submit %>
    </p>
<% end %>
<%= link_to 'Back', items_path %>

store/app/views/items/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @item.item_name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @item.description %>
</p>
<%= link_to 'Catalog', items_path %>

store/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Store</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

store/app/views/persons/profile.html.erb
<h1>Persons#profile</h1>
<p>Find me in app/views/persons/profile.html.erb</p>

store/app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>
<%= link_to 'Catalog', controller: 'items' %>